spring.datasource.url=jdbc:postgresql://localhost:5432/project008
spring.datasource.username=prostgres008
spring.datasource.password=38329

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect